### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by PritiShah** [formvalidation/support#204] opened 2015-07-13 17:29 UTC
Hello, 

I am not able to figure out what am I doing wrong here, but the submit button does not seem to do anything and .on('success.form.fv', function(e)  seems to be recursive. I have read about the complex form errors and the .form-group requirement, but still am not able to figure out this error - 
"Uncaught RangeError: Maximum call stack size exceeded" in my context .My jsp does pass multiple files. I do have a postAjax method defined in my JS file and would like to keep it that way and not include in this formValidation framework if possible. I have  read the ajax-submit-form-data and ajax-submit-formdata-with-files example, but since I have already methods of ajax-submit with and without files defined, i dont wont to change it and keep it with my js file.
 Can you pl. suggest if that is possible and if so what I might be doing wrong here. Thanks.

submitNewSection.jsp

```
< form name ="newSectionSubmitForm" id="newSectionSubmitForm"  class="form-horizontal formCenter" role="form" method="post" ENCTYPE="multipart/form-data">
	<input type="hidden" id="tableImageRowCount" name="tableImageRowCount" />
	<input type="hidden" id="tableAnswerRowCount" name="tableAnswerRowCount" />
		
		 <div class="form-group">
	         <label for="category"  class="col-sm-3 control-label">Category <span class="color-red">*</span></label>
	           
	         <div class="col-sm-6">
	            <select id="category" name="category" class="form-control" onchange="onChangeCategoryDisableSubCategory();return false;">
	               <option value="Hematology" >Hematology</option>
	               <option value="Oncology" >Oncology</option>
	            </select>
	         </div>
	      </div>
	      
	      <div class="form-group">
	         <label for="subCategory"  class="col-sm-3 control-label">Sub Category</label>
	               
	         <div class="col-sm-6">
	            <select id="subCategory" name ="subCategory" class="form-control">
	            	<option></option>
	               <option>Benign</option>
	               <option>Malignant</option>
	            </select>
	         </div>
	      </div>
	      
	      <div class="form-group">
     		 <label for="sectionName" class="col-sm-3 control-label">Section Name <span class="color-red">*</span></label>
         	 <div class="col-sm-9">
		         <textarea class="form-control" id="sectionName" name="sectionName" rows="2"/>
		     </div>
   		  </div>
   		  
   		  <div class="form-group">
     		 <label for="sectionDisplayOrder" class="col-sm-3 control-label">Section Display Order <span class="color-red">*</span></label>
         	 <div class="col-sm-3">
		         <input class="form-control" name="sectionDisplayOrder" id="sectionDisplayOrder" type="number" min="1"/>
		     </div>
   		  </div>
   		  
   		  <div class="form-group">
     		 <label for="subSectionName" class="col-sm-3 control-label">Sub Section Name <span class="color-red">*</span></label>
         	 <div class="col-sm-9">
		         <textarea class="form-control" name="subSectionName" id="subSectionName" rows="2"/>
		     </div>
   		  </div>
   		  
   		  <div class="form-group">
     		 <label for="subSectionDisplayOrder" class="col-sm-3 control-label">Sub Section Display Order <span class="color-red">*</span></label>
         	 <div class="col-sm-3">
		         <input class="form-control" name="subSectionDisplayOrder" id="subSectionDisplayOrder" type="number" min="1" />
		     </div>
   		  </div>
   		  
   		  <div class="form-group">
     		 <label for="caseNo" class="col-sm-3 control-label">Case No. <span class="color-red">*</span></label>
         	 <div class="col-sm-3">
		         <input class="form-control" name="caseNo" id="caseNo" type="number" min="1" />
		     </div>
   		  </div>
   		  
   		  <div class="form-group">
     		 <label for="caseName" class="col-sm-3 control-label">Case Name <span class="color-red">*</span></label>
         	 <div class="col-sm-9">
		         <textarea class="form-control" name="caseName" id="caseName" rows="2"/>
		     </div>
   		  </div>

		  <div class="form-group">
     		 <label for="caseLearningObj" class="col-sm-3 control-label">Case Learning Obj. <span class="color-red">*</span></label>
         	 <div class="col-sm-9">
		         <textarea class="form-control" name="caseLearningObj" id="caseLearningObj" rows="2"/>
		     </div>
   		  </div>
		
		  <div class="form-group">
     		 <label for="questionDesc" class="col-sm-3 control-label">Question Desc <span class="color-red">*</span></label>
         	 <div class="col-sm-9">
		         <textarea class="form-control" name="questionDesc" id="questionDesc" rows="4"/>
		     </div>
   		  </div>

		  <div class="form-group">
     		 <label for="questionToAsk" class="col-sm-3 control-label">Question <span class="color-red">*</span></label>
         	 <div class="col-sm-9">
		         <textarea class="form-control" name="questionToAsk" id="questionToAsk" rows="2"/>
		     </div>
   		  </div>


		<div class="form-group">
     		 <label for="author" class="col-sm-3 control-label">Author <span class="color-red">*</span></label>
         	 <div class="col-sm-3">
		         <input class="form-control" name="author" id="author" type="text" />
		        
		     </div>
   		  </div>
   		  
   		  		
		<div class="form-group spacer-top">
     		 <label for="tableImage" class="col-sm-3 control-label">Image Details</label>
         	
    	 	 <div class="col-md-9">
    			<table class="table table-striped table-hover table-bordered pull-right" id="tableImage" name="tableImage" >
    				<thead>
						<tr >
							<th class="text-center col-md-1 column"> # </th>
							<th class="text-center col-md-5 column"> Desc </th>
							<th class="text-center col-md-4 column"> Upload File </th>
							<th class="text-center col-md-2 column"> Delete </th>
							
						</tr>
					</thead>
					<tbody>
					<tr>
						<td>1</td>
    					<td><input type="text" id="imageDesc0" name="imageDesc0" class="form-control"/></td>    
    					<td><input type="file" id="imageFile0" name="imageFile0"  /></td>   
    					<td class="deleterow"><div class="glyphicon glyphicon-remove"></div></td>
    				</tr>
    				</tbody>
   				 </table>
			
			<a class="btn btn-info addNewImageRow pull-left">Add New <span class="glyphicon glyphicon-plus"></span></a>
			</div>
		</div>
		
		
		
	

		<div class="form-group  spacer-top">
     		 <label for="tableAnswer" class="col-sm-3 control-label">Answer Details <span class="color-red">*</span></label>
        
			 <div class="col-md-9">
	    			<table class="table table-striped table-hover table-bordered pull-right" id="tableAnswer" name="tableAnswer">
	    				<thead>
							<tr >
								<th class="text-center col-md-1 column"> # </th>
								<th class="text-center col-md-4 column"> Description </th>
								<th class="text-center col-md-4 column"> Explanation </th>
								<th class="text-center col-md-2 column"> Is Correct Answer </th>
								<th class="text-center col-md-1 column"> Delete </th>
								
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>1</td>
		    					<td><textarea class="form-control" id="answerDesc0"  name="answerDesc0" rows="4"/></td>    
		    					<td><textarea class="form-control" id="answerExplanation0"  name="answerExplanation0"  rows="4"/></td>   
		    					<td><select  class="form-control" id="isAnswerCorrect0" name="isAnswerCorrect0" >
								               <option value="No">No</option>
								               <option value="Yes">Yes</option>
					            	</select>
					            </td>
		    					<td class="deleterow"><div class="glyphicon glyphicon-remove"></div></td>
		    				</tr>
	    				</tbody>
	   				 </table>
				
				<a class="btn btn-info addNewAnswerRow pull-left">Add New <span class="glyphicon glyphicon-plus"></span></a>
			</div>
		</div>
	
	
	 <div class="controls spacer-top">
 		<button class="btn btn-default btn-lg pull-right" onclick="cancelPage();return false;">Cancel</button>
 		<button type="submit" class="btn btn-primary btn-lg pull-right spacer-right" >Submit Section</button>
 		 
 		
 	</div>	
	
	

	</form><!-- top level form -->
	
<script>
	
	onloadInitiatializeImageGrid();
	onloadInitiatializeAnswerGrid();
	validateNewSectionSubmitForm();
</script>
```

hemoncCBCFunctions.js
```
function submitNewSection(targetUrl, form) {

		if (!validateCorrectNoOfAnswers()) return;
	
		postAjaxDataWithImageFile(null, 'content', targetUrl, form, null, null);

}
```

hemoncCBCValidations.js
```
function validateNewSectionSubmitForm(){
	
	
	$('#newSectionSubmitForm').formValidation({
		 // Only disabled elements are excluded
        // The invisible elements belonging to inactive tabs must be validated
        excluded: [':disabled'],
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
        	category: {
                validators: {
                    notEmpty: {
                        message: 'Category is Required.'
                    }
                }
            },
            sectionName:{
            	validators: {
                    notEmpty: {
                        message: 'Section name is Required.'
                    }
                }
            },
            sectionDisplayOrder:{
            	validators: {
                    notEmpty: {
                        message: 'Section Display Order is Required.'
                    }
                }
            },
            subSectionName:{
            	validators: {
                    notEmpty: {
                        message: 'SubSection name is Required.'
                    }
                }
            },
            subSectionDisplayOrder:{
            	validators: {
                    notEmpty: {
                        message: 'SubSectionDisplayOrder is Required.'
                    }
                }
            },
            caseNo:{
            	validators: {
                    notEmpty: {
                        message: 'Case No. is Required.'
                    }
                }
            },
            caseName:{
            	validators: {
                    notEmpty: {
                        message: 'Case Name is Required.'
                    }
                }
            },
            caseLearningObj:{
            	validators: {
                    notEmpty: {
                        message: 'Case Learning Objective is Required.'
                    }
                }
            },
            questionDesc:{
            	validators: {
                    notEmpty: {
                        message: 'Question Description is Required.'
                    }
                }
            },
            questionToAsk:{
            	validators: {
                    notEmpty: {
                        message: 'Question To Ask is Required.'
                    }
                }
            },
            author:{
            	validators: {
                    notEmpty: {
                        message: 'Author is Required.'
                    }
                }
            },
            answerDesc0:{
            	validators: {
                    notEmpty: {
                        message: 'Answer Description is Required.'
                    }
                }
            },
            answerExplanation0:{
            	validators: {
                    notEmpty: {
                        message: 'Answer Explanation is Required.'
                    }
                }
            },
            
    
        }    
             
        
	 
	})
	.on('success.form.fv', function(e) {
         e.preventDefault();
         alert('yes');    // alert statement -- keeps going on - recursive at submit button.
         var $form = $(e.target);     
         var formName = $form.attr('name');
        
         
         submitNewSection('submitNewSection.html',formName);   //calls Ajax function defined in another JS

         $form.formValidation('disableSubmitButtons', false);
    });
     
	 return true;
	
		
}
```

Thanks a lot.
Priti

**Comment by nghuuphuoc** [comment] 2015-07-14 10:23
The problem is not caused by the form structure because the form structure is standard, each field is placed inside a `.form-group` element.

You got the `Uncaught RangeError: Maximum call stack size exceeded` issue because of an infinite loop.
Let's imagine that 
* When you submit the form, all fields are valid, so it triggers the `success.form.fv` event.
* And then you call `submitNewSection('submitNewSection.html',formName);` which will call `validateCorrectNoOfAnswers()`.
This will validate some fields, and will trigger the `success.form.fv` event again if all answers are correct.

So, you will be in an infinite loop.

To solve the issue, you need to adjust the `submitNewSection` method.

**Comment by PritiShah** [comment] 2015-07-14 19:52
Hello Phuoc,
I see your point but am still not getting it right. There's nothing much i can do about submitNewSection() method. Also, its working fine without the validation framework.

Q1. - is it ok to define submit action on "onclick" event of the submit button. How would that affect the 
 .on('success.form.fv', function(e)  -- event call? Which should trigger first? In my case both are getting triggered not in the same order always and it causes some uncertainty with the result.

Q2 - Another scenerio - lets say i do not call  .on('success.form.fv', function(e)  event. 
But on click event of submit button, i have an alert statment that is being called and the submit button then gets disabled inspite of the all the fields being valid. If I write this after alert is called - 
"  $('#' + form).formValidation('disableSubmitButtons', false);" then submit button is disabled and when i press the submit button after that it does not submit.

Here are the files some reference to my questions - 

Assuming my fields are in proper bootstrap form inside .form-group class
how should the following play out :  

-- I have  submit button in my jsp with onclick event as - 

JSP--(button tag is appropriate in my file, just skewed it here for the preview)

 <
button type="submit" class="btn btn-primary btn-lg pull-right spacer-right" onclick="submitNewSection('submitNewSection.html','newSectionSubmitForm');return false">Submit Section </button
>
 
JS -- 
function submitNewSection(targetUrl, form) {

	if (!validateCorrectNoOfAnswers() ){
            alert ('Not proper');  
            return false;    
        } 

	
	//var isFormValid = $('#' + form).data('formValidation').validate().isValid();  //not sure to use manual validation or not if  .on('success.form.fv', function(e)  is not defined specifically.
	
	//if (isFormValid) {

		var tableImageRowCount = $('#tableImage tr').length - 1;
		var tableAnswerRowCount = $('#tableAnswer tr').length - 1;
	
		$('#tableImageRowCount').val(tableImageRowCount);
		$('#tableAnswerRowCount').val(tableAnswerRowCount);
	
		postAjaxDataWithImageFile(null, 'content', targetUrl, form, null, null);
	//}	

}


function validateNewSectionSubmitForm(){
	
	
	$('#newSectionSubmitForm').formValidation({
		 // Only disabled elements are excluded
        // The invisible elements belonging to inactive tabs must be validated
        excluded: [':disabled'],
        framework: 'bootstrap',
        icon: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
        	category: {
                validators: {
                    notEmpty: {
                        message: 'Category is Required.'
                    }
                }
            },
            sectionName:{
            	validators: {
                    notEmpty: {
                        message: 'Section name is Required.'
                    }
                }
            },
            subCategory:{
            	validators: {
                    notEmpty: {
                    	enabled: true,
                        message: 'Sub Category is Required only for Hematology.'
                    }
                }
            },
            sectionDisplayOrder:{
            	validators: {
                    notEmpty: {
                        message: 'Section Display Order is Required.'
                    }
                }
            },
            subSectionName:{
            	validators: {
                    notEmpty: {
                        message: 'SubSection name is Required.'
                    }
                }
            },
            subSectionDisplayOrder:{
            	validators: {
                    notEmpty: {
                        message: 'SubSectionDisplayOrder is Required.'
                    }
                }
            },
            caseNo:{
            	validators: {
                    notEmpty: {
                        message: 'Case No. is Required.'
                    }
                }
            },
            caseName:{
            	validators: {
                    notEmpty: {
                        message: 'Case Name is Required.'
                    }
                }
            },
            caseLearningObj:{
            	validators: {
                    notEmpty: {
                        message: 'Case Learning Objective is Required.'
                    }
                }
            },
            questionDesc:{
            	validators: {
                    notEmpty: {
                        message: 'Question Description is Required.'
                    }
                }
            },
            questionToAsk:{
            	validators: {
                    notEmpty: {
                        message: 'Question To Ask is Required.'
                    }
                }
            },
            author:{
            	validators: {
                    notEmpty: {
                        message: 'Author is Required.'
                    }
                }
            },
            answerDesc0:{
            	validators: {
                    notEmpty: {
                        message: 'Answer Description is Required.'
                    }
                }
            },
            answerExplanation0:{
            	validators: {
                    notEmpty: {
                        message: 'Answer Explanation is Required.'
                    }
                }
            },
            
    
        }    
             
        
	 
	});

       /*
	.on('success.form.fv', function(e) {
         e.preventDefault();
         alert('yes');
         
         var $form = $(e.target);  
         fv    = $(e.target).data('formValidation');
         
         var formName = $form.attr('name');
                
         $form.formValidation('disableSubmitButtons', false);
         //fv.defaultSubmit();
*/

    });
     
	 return true;
	
		
}


Thanks  a lot!

**Comment by PritiShah** [comment] 2015-07-16 16:58
Hello,

Thank you for the wonderful product and its support. 

This might  be primitive, but I was wondering if you might have an example where formvalidation is used along with submit button's onclick event. 

Thanks much,
Priti

**Comment by nghuuphuoc** [comment] 2015-07-23 02:36
Since a simillar issue (#218) is solved, can we close this issue?

**Comment by PritiShah** [comment] 2015-07-23 02:39
Sure, it was the same issue as in #218.

**Closed** 2015-07-24 14:37 UTC
Labels: question
